[package]
authors = ["babilado developers"]
edition = "2018"
license = "MIT OR Apache-2.0"
name = "babilado-client"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
babilado-types = "0.2.1"
jsonl = "4.0"
rand = "0.8.2"
